"""add detailed calculation fields for billing and exchange

Revision ID: 1142f56febf2
Revises: bd7c78fd3e47
Create Date: 2026-08-06 19:11:35.431686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1142f56febf2'
down_revision: Union[str, Sequence[str], None] = 'bd7c78fd3e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.add_column('exchange_items', sa.Column('wastage', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('exchange_items', sa.Column('fine_weight', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('exchange_items', sa.Column('labour_charge', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_items', sa.Column('testing_melting_charge', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_items', sa.Column('hallmark_charge', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_items', sa.Column('other_charges', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_items', sa.Column('discount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_new_items', sa.Column('gross_weight', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('exchange_new_items', sa.Column('stone_weight', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('exchange_new_items', sa.Column('touch_purity', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('exchange_new_items', sa.Column('wastage', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('exchange_new_items', sa.Column('fine_weight', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('exchange_new_items', sa.Column('making_charge_type', sa.String(length=20), nullable=False))
    op.add_column('exchange_new_items', sa.Column('making_charge_rate', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_new_items', sa.Column('making_charges_amount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_new_items', sa.Column('hallmark_charges', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_new_items', sa.Column('other_charges', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_new_items', sa.Column('discount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('exchange_new_items', sa.Column('rate_applied', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('gold_calculations', sa.Column('touch_purity', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('gold_calculations', sa.Column('wastage', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('gold_calculations', sa.Column('fine_weight', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('gold_calculations', sa.Column('other_charges', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('gold_calculations', sa.Column('discount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('gold_calculations', 'pure_weight')
    op.drop_column('gold_calculations', 'tanch_percentage')
    op.drop_column('invoices', 'fine_gold_deposited')
    op.drop_column('invoices', 'fine_silver_billed')
    op.drop_column('invoices', 'metal_settlement_mode')
    op.drop_column('invoices', 'fine_silver_deposited')
    op.drop_column('invoices', 'fine_gold_billed')
    op.add_column('silver_calculations', sa.Column('wastage', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('silver_calculations', sa.Column('other_charges', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('silver_calculations', sa.Column('discount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('stock_items', 'wastage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_items', sa.Column('wastage', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('silver_calculations', 'discount')
    op.drop_column('silver_calculations', 'other_charges')
    op.drop_column('silver_calculations', 'wastage')
    op.add_column('invoices', sa.Column('fine_gold_billed', mysql.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('invoices', sa.Column('fine_silver_deposited', mysql.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('invoices', sa.Column('metal_settlement_mode', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('fine_silver_billed', mysql.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('invoices', sa.Column('fine_gold_deposited', mysql.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('gold_calculations', sa.Column('tanch_percentage', mysql.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('gold_calculations', sa.Column('pure_weight', mysql.DECIMAL(precision=10, scale=3), nullable=False))
    op.drop_column('gold_calculations', 'discount')
    op.drop_column('gold_calculations', 'other_charges')
    op.drop_column('gold_calculations', 'fine_weight')
    op.drop_column('gold_calculations', 'wastage')
    op.drop_column('gold_calculations', 'touch_purity')
    op.drop_column('exchange_new_items', 'rate_applied')
    op.drop_column('exchange_new_items', 'discount')
    op.drop_column('exchange_new_items', 'other_charges')
    op.drop_column('exchange_new_items', 'hallmark_charges')
    op.drop_column('exchange_new_items', 'making_charges_amount')
    op.drop_column('exchange_new_items', 'making_charge_rate')
    op.drop_column('exchange_new_items', 'making_charge_type')
    op.drop_column('exchange_new_items', 'fine_weight')
    op.drop_column('exchange_new_items', 'wastage')
    op.drop_column('exchange_new_items', 'touch_purity')
    op.drop_column('exchange_new_items', 'stone_weight')
    op.drop_column('exchange_new_items', 'gross_weight')
    op.drop_column('exchange_items', 'discount')
    op.drop_column('exchange_items', 'other_charges')
    op.drop_column('exchange_items', 'hallmark_charge')
    op.drop_column('exchange_items', 'testing_melting_charge')
    op.drop_column('exchange_items', 'labour_charge')
    op.drop_column('exchange_items', 'fine_weight')
    op.drop_column('exchange_items', 'wastage')
    op.create_table('audit_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('entity_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('changes', mysql.JSON(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    # ### end Alembic commands ###
