"""Add hybrid metal balance fields

Revision ID: a48d02fb554c
Revises: d833ecfa4fa6
Create Date: 2026-09-19 23:01:52.206841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a48d02fb554c'
down_revision: Union[str, Sequence[str], None] = 'd833ecfa4fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('gold_balance_metal_weight', sa.DECIMAL(precision=12, scale=3), nullable=True))
    op.add_column('invoices', sa.Column('silver_balance_metal_weight', sa.DECIMAL(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'silver_balance_metal_weight')
    op.drop_column('invoices', 'gold_balance_metal_weight')
    # ### end Alembic commands ###
