"""Add metal balances to ledgers and crm

Revision ID: b3b75aaeac27
Revises: b7cb22beb804
Create Date: 2026-08-02 08:41:50.902001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3b75aaeac27'
down_revision: Union[str, Sequence[str], None] = 'b7cb22beb804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_ledgers', sa.Column('gold_debit', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('customer_ledgers', sa.Column('gold_credit', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('customer_ledgers', sa.Column('gold_balance', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('customer_ledgers', sa.Column('silver_debit', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('customer_ledgers', sa.Column('silver_credit', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('customer_ledgers', sa.Column('silver_balance', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('customers', sa.Column('fine_gold_balance', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('customers', sa.Column('fine_silver_balance', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('sellers', sa.Column('fine_gold_balance', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('sellers', sa.Column('fine_silver_balance', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('supplier_ledgers', sa.Column('gold_debit', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('supplier_ledgers', sa.Column('gold_credit', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('supplier_ledgers', sa.Column('gold_balance', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('supplier_ledgers', sa.Column('silver_debit', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('supplier_ledgers', sa.Column('silver_credit', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('supplier_ledgers', sa.Column('silver_balance', sa.DECIMAL(precision=10, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('supplier_ledgers', 'silver_balance')
    op.drop_column('supplier_ledgers', 'silver_credit')
    op.drop_column('supplier_ledgers', 'silver_debit')
    op.drop_column('supplier_ledgers', 'gold_balance')
    op.drop_column('supplier_ledgers', 'gold_credit')
    op.drop_column('supplier_ledgers', 'gold_debit')
    op.alter_column('silver_rates', 'rate_per_gram',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_silver_calculations_metal_rate_id'), 'silver_calculations', ['metal_rate_id'], unique=False)
    op.add_column('settings', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.alter_column('settings', 'value',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=False)
    op.alter_column('settings', 'key',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('sellers', 'fine_silver_balance')
    op.drop_column('sellers', 'fine_gold_balance')
    op.create_index(op.f('ix_purities_metal_type_id'), 'purities', ['metal_type_id'], unique=False)
    op.create_index(op.f('ix_product_variants_purity_id'), 'product_variants', ['purity_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_inventory_item_id'), 'invoice_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_warehouse_id'), 'inventory_items', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_product_variant_id'), 'inventory_items', ['product_variant_id'], unique=False)
    op.drop_index(op.f('ix_inventory_item_code'), table_name='inventory')
    op.alter_column('inventory', 'item_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('gold_rates', 'rate_per_gram',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_gold_calculations_metal_rate_id'), 'gold_calculations', ['metal_rate_id'], unique=False)
    op.alter_column('customers', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('customers', 'fine_silver_balance')
    op.drop_column('customers', 'fine_gold_balance')
    op.drop_column('customer_ledgers', 'silver_balance')
    op.drop_column('customer_ledgers', 'silver_credit')
    op.drop_column('customer_ledgers', 'silver_debit')
    op.drop_column('customer_ledgers', 'gold_balance')
    op.drop_column('customer_ledgers', 'gold_credit')
    op.drop_column('customer_ledgers', 'gold_debit')
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('entity', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###
