"""Add partial and completed statuses

Revision ID: bd7c78fd3e47
Revises: b3b75aaeac27
Create Date: 2026-08-02 11:18:14.359341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd7c78fd3e47'
down_revision: Union[str, Sequence[str], None] = 'b3b75aaeac27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_gold_calculations_metal_rate_id'), table_name='gold_calculations')
    op.alter_column('gold_rates', 'rate_per_gram',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('inventory', 'item_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_inventory_item_code'), 'inventory', ['item_code'], unique=True)
    op.drop_index(op.f('ix_inventory_items_product_variant_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_warehouse_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_invoice_items_inventory_item_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.alter_column('invoices', 'status',
               existing_type=mysql.ENUM('DRAFT', 'PAID', 'CANCELLED'),
               type_=sa.Enum('DRAFT', 'PARTIAL', 'PAID', 'COMPLETED', 'CANCELLED', name='invoicestatus'),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_purity_id'), table_name='product_variants')
    op.drop_index(op.f('ix_purities_metal_type_id'), table_name='purities')
    op.alter_column('settings', 'key',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('settings', 'value',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_column('settings', 'updated_at')
    op.drop_index(op.f('ix_silver_calculations_metal_rate_id'), table_name='silver_calculations')
    op.alter_column('silver_rates', 'rate_per_gram',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('silver_rates', 'rate_per_gram',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_silver_calculations_metal_rate_id'), 'silver_calculations', ['metal_rate_id'], unique=False)
    op.add_column('settings', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.alter_column('settings', 'value',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=False)
    op.alter_column('settings', 'key',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_purities_metal_type_id'), 'purities', ['metal_type_id'], unique=False)
    op.create_index(op.f('ix_product_variants_purity_id'), 'product_variants', ['purity_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('DRAFT', 'PARTIAL', 'PAID', 'COMPLETED', 'CANCELLED', name='invoicestatus'),
               type_=mysql.ENUM('DRAFT', 'PAID', 'CANCELLED'),
               existing_nullable=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_inventory_item_id'), 'invoice_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_warehouse_id'), 'inventory_items', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_product_variant_id'), 'inventory_items', ['product_variant_id'], unique=False)
    op.drop_index(op.f('ix_inventory_item_code'), table_name='inventory')
    op.alter_column('inventory', 'item_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('gold_rates', 'rate_per_gram',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_gold_calculations_metal_rate_id'), 'gold_calculations', ['metal_rate_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('entity_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('changes', mysql.JSON(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    # ### end Alembic commands ###
