"""Add settlement_metal_type

Revision ID: d55dd9c4ce98
Revises: d71fe25ed13a
Create Date: 2026-09-19 19:03:56.554856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd55dd9c4ce98'
down_revision: Union[str, Sequence[str], None] = 'd71fe25ed13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('invoices', sa.Column('settlement_metal_type', sa.Enum('Gold', 'Silver', name='metaltype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'settlement_metal_type')

    # ### end Alembic commands ###
