"""Add hybrid billing settlement fields

Revision ID: d71fe25ed13a
Revises: 1142f56febf2
Create Date: 2026-09-19 19:01:40.800369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd71fe25ed13a'
down_revision: Union[str, Sequence[str], None] = '1142f56febf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('invoices', sa.Column('bill_type', sa.Enum('Cash', 'Metal', 'Hybrid', name='billtype'), nullable=False))
    op.add_column('invoices', sa.Column('settlement_type', sa.Enum('Cash', 'Metal', name='settlementtype'), nullable=False))
    op.add_column('invoices', sa.Column('metal_received_value', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('cash_received', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('balance_amount', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('balance_metal_weight', sa.DECIMAL(precision=12, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'balance_metal_weight')
    op.drop_column('invoices', 'balance_amount')
    op.drop_column('invoices', 'cash_received')
    op.drop_column('invoices', 'metal_received_value')
    op.drop_column('invoices', 'settlement_type')
    op.drop_column('invoices', 'bill_type')

    # ### end Alembic commands ###
