"""Add stone_weight to silver_calculations

Revision ID: d833ecfa4fa6
Revises: d55dd9c4ce98
Create Date: 2026-09-19 22:48:07.588169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd833ecfa4fa6'
down_revision: Union[str, Sequence[str], None] = 'd55dd9c4ce98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silver_calculations', sa.Column('stone_weight', sa.DECIMAL(precision=10, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('silver_calculations', 'stone_weight')
    # ### end Alembic commands ###
